// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG8gVUtytAkJz1Ymxu_0X7Mq3Iywvhahg',
    appId: '1:339846967360:web:b9fab656451725c7792fa5',
    messagingSenderId: '339846967360',
    projectId: 'fireship-lessons-86396',
    authDomain: 'fireship-lessons-86396.firebaseapp.com',
    storageBucket: 'fireship-lessons-86396.appspot.com',
    measurementId: 'G-V36DJLFJ9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwfr__JWiVizd7Wt9Jzbo_kUijcogCfZY',
    appId: '1:339846967360:android:dc0df852bd8a5b42792fa5',
    messagingSenderId: '339846967360',
    projectId: 'fireship-lessons-86396',
    storageBucket: 'fireship-lessons-86396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ9FiBJQznN9SbnTsDBFBJrxT2E2QI1kw',
    appId: '1:339846967360:ios:dfb05813baac841c792fa5',
    messagingSenderId: '339846967360',
    projectId: 'fireship-lessons-86396',
    storageBucket: 'fireship-lessons-86396.appspot.com',
    androidClientId: '339846967360-419la6av73ke11il91pnt7fnl0eplsc2.apps.googleusercontent.com',
    iosClientId: '339846967360-8fgdka50k820495r07vont83sd6j64v3.apps.googleusercontent.com',
    iosBundleId: 'io.fireship.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ9FiBJQznN9SbnTsDBFBJrxT2E2QI1kw',
    appId: '1:339846967360:ios:dfb05813baac841c792fa5',
    messagingSenderId: '339846967360',
    projectId: 'fireship-lessons-86396',
    storageBucket: 'fireship-lessons-86396.appspot.com',
    androidClientId: '339846967360-419la6av73ke11il91pnt7fnl0eplsc2.apps.googleusercontent.com',
    iosClientId: '339846967360-8fgdka50k820495r07vont83sd6j64v3.apps.googleusercontent.com',
    iosBundleId: 'io.fireship.quizapp',
  );
}
